name: deploy burimi app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r ${{ github.sha }}.zip . -x "*.git*" node_modules

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: burimi-server
          environment_name: Burimi-server-env
          version_label: ${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ap-northeast-2
          deployment_package: ${{ github.sha }}.zip
